### ISSUE TITLE
Unexpected type

### ISSUE THREAD

**Issue by hodovani** [TRI-AMDD/CAMD#302]
The issue line [here](https://github.com/TRI-AMDD/CAMD/blob/master/camd/agent/stability.py#L581).

`apply_gradients` expects a list, but receives an iterator (from call to zip, which returns an iterator). Should we convert to list for Python 3 compatibility?

**Comment by JosephMontoya-TRI** [comment]
Hi, and thank you for the suggestion!  I had to refactor this method wholesale to be consistent with the latest version of gpflow, so I think this issue is moot, but if that's not the case, feel free to reopen and let us know.
