### ISSUE TITLE
Are scripts available for "Agents for sequential learning using multiple-fidelity data"?

### ISSUE THREAD

**Issue by sgbaird** [TRI-AMDD/CAMD#537]
As I was reading [the manuscript](https://doi.org/10.1038/s41598-022-08413-8), I was curious about what a comparison with [Dragonfly via RayTune](https://docs.ray.io/en/latest/tune/api_docs/suggestion.html#dragonfly-tune-suggest-dragonfly-dragonflysearch) or [Ax](https://github.com/facebook/Ax/issues/475) (latter would just be for small data experiments).

**Comment by JosephMontoya-TRI** [comment]
Hi @sgbaird, apologies for the delay - my notification settings were misconfigured so I'm just seeing this now.  We don't have a script per se, but the [MultiFidelity test](https://github.com/TRI-AMDD/CAMD/blob/main/camd/campaigns/tests/test_multi_fidelity.py) provides examples of the invocation of each multi-fidelity agent along with a campaign. Is this enough to get started on such a comparison?
